export const educationItems = [
  {
    period: "2022 - 2024",
    degree: "TECHNICAL DEGREE (DTS)",
    spec: "Digital Development — Full Stack Option",
    institution:
      "Specialized Institute of Applied Technology Ntic Sidi Youssef Ben Ali",
    location: "Marrakech, Morocco",
    tags: [
      "HTML/CSS",
      "JavaScript",
      "PHP",
      "Python",
      "UML",
      "Object Oriented Programming",
      "Laravel",
      "React JS",
      "DevOps",
      "MySQL",
      "RabbitMQ",
      "Express JS",
      "Docker",
      "Microsoft Azure",
      "Full Stack",
      "Agile Methodology",
    ],
  },
  {
    period: "2024 - 2025",
    degree: "BACHELOR'S IN COMPUTER ENGINEERING",
    spec: "Digital Governance",
    institution: "Higher School of Technology (EST)",
    location: "Kénitra, Morocco",
    tags: [
      "Advanced UML",
      "Java",
      "IT Infrastructor and Systems Administration",
      "Spring Framework",
      "Spring Boot",
      "Jakartaa EE",
      "Microservices",
      "REST APIs",
      "SQL & NoSQL Databases",
      "Digital Governance",
      "IT Projects Administrations and Auditing",
      "Systems Design",
      "DevOps",
      "Design Patterns",
      "Mobile Development",
      "React Native",
      "PL/SQL",
      "Advanced Networking",
    ],
  },
  {
    period: "2025 - 2027",
    degree: "INFORMATION SYSTEMS ENGINEERING",
    spec: "Faculty of Sciences Semlalia",
    institution: "Cadi Ayyad University",
    location: "Marrakech, Morocco",
    tags: [
      "Spring Boot",
      "Software Engineering",
      "Web Development Mythologies",
      "Distributed Systems",
      "DevOps and Agile Approaches",
      "Machine Learning Techniques",
      "Cloud Architecture",
    ],
  },
];
