export const projects = [
  {
    id: "01",
    name: "DANDILION",
    desc: "Cross-platform desktop media downloader with a clean PySide6 GUI. Archives YouTube content offline via yt-dlp with format selection and queue management.",
    tech: ["Python", "PySide6", "PyQt6", "yt-dlp", "Qt"],
    stars: 3,
    url: "https://github.com/AmbitiousFlowDev/Dandilion",
    category: "DESKTOP APPLICATION",
  },
  {
    id: "02",
    name: "STRATQUEST",
    desc: "Gamified Mobile Cloud-Based Learning Management System for Strategic Management education. Full-stack TypeScript platform with cloud deployment and mobile-first design.",
    tech: ["TypeScript", "Mobile", "Cloud", "LMS"],
    stars: 2,
    url: "https://github.com/AmbitiousFlowDev/StratQuest",
    category: "PLATFORM",
  },
  {
    id: "03",
    name: "INTERNCONNECT",
    desc: "Peer-to-peer platform bridging the internship information gap for Moroccan students. Robust Java backend with custom P2P data architecture.",
    tech: ["Java", "P2P", "Backend"],
    stars: 1,
    url: "https://github.com/AmbitiousFlowDev/InternConnect",
    category: "SOCIAL PLATFORM",
  },
  {
    id: "04",
    name: "GENETIC DISORDER CLASSIFIER",
    desc: "Machine learning classifier for genetic disorder detection from genomic datasets. Applies Scikit-learn pipelines to bioinformatics data in Jupyter Notebooks.",
    tech: ["Python", "Jupyter", "Scikit-learn", "ML", "Genomics"],
    stars: 1,
    url: "https://github.com/AmbitiousFlowDev/GeneticDissorderClassifier",
    category: "ML / RESEARCH",
  },
  {
    id: "05",
    name: "E-LIBRARY",
    desc: "Advanced library management system with intelligent search and reservation workflows. React frontend, Spring Boot REST API, and MySQL with role-based access.",
    tech: ["React", "Spring Boot", "MySQL", "JavaScript"],
    stars: 1,
    url: "https://github.com/AmbitiousFlowDev/E-Library",
    category: "WEB APPLICATION",
  },
  {
    id: "06",
    name: "SONA",
    desc: "Minimal Discord bot enhancing server experience with custom automation, commands, and event handling. Built with the Disnake Python framework.",
    tech: ["Python", "Discord", "Disnake", "Bot"],
    stars: 1,
    url: "https://github.com/AmbitiousFlowDev/Sona",
    category: "BOT / AUTOMATION",
  },
];
