

export const projects = [
  {
    id: "01",
    name: "DANDILION",
    desc: "Cross-platform desktop media downloader with a clean PySide6 GUI. Archives YouTube content offline via yt-dlp with format selection and queue management.",
    tech: ["Python", "PySide6", "PyQt6", "yt-dlp", "Qt"],
    url: "https://github.com/AmbitiousFlowDev/Dandilion",
    category: "DESKTOP APPLICATION",
  },
  {
    id: "02",
    name: "STRATQUEST",
    desc: "Gamified Mobile Cloud-Based Learning Management System for Strategic Management education. Full-stack TypeScript platform with cloud deployment and mobile-first design.",
    tech: ["TypeScript", "Mobile", "Cloud", "LMS"],
    url: "https://github.com/AmbitiousFlowDev/StratQuest",
    category: "PLATFORM",
  },
  {
    id: "03",
    name: "STABLE DIFFUSION UI",
    desc: "Web interface for local Stable Diffusion image generation. Wraps HuggingFace's diffusers library in a Streamlit UI with CUDA-accelerated inference and database-backed generation history.",
    tech: ["Python", "PyTorch", "Streamlit", "HuggingFace", "CUDA"],
    url: "https://github.com/AmbitiousFlowDev/StableDiffusion-UI",
    category: "ML / GENERATIVE AI",
  },
  {
    id: "04",
    name: "TSMS",
    desc: "Telephone Staffing Management System. Full CRUD Laravel application for managing staff allocations and assignments, with a Filament admin panel and role-based access control.",
    tech: ["Laravel", "PHP", "Vue.js", "Filament", "SQLite"],
    url: "https://github.com/AmbitiousFlowDev/TSMS",
    category: "WEB APPLICATION",
  },
  {
    id: "05",
    name: "INTERNCONNECT",
    desc: "Peer-to-peer platform bridging the internship information gap for Moroccan students. Robust Java backend with custom P2P data architecture.",
    tech: ["Java", "P2P", "Backend"],
    url: "https://github.com/AmbitiousFlowDev/InternConnect",
    category: "SOCIAL PLATFORM",
  },
  {
    id: "06",
    name: "GENETIC DISORDER CLASSIFIER",
    desc: "Machine learning classifier for genetic disorder detection from genomic datasets. Applies Scikit-learn pipelines to bioinformatics data in Jupyter Notebooks.",
    tech: ["Python", "Jupyter", "Scikit-learn", "ML", "Genomics"],
    url: "https://github.com/AmbitiousFlowDev/GeneticDissorderClassifier",
    category: "ML / RESEARCH",
  },
  {
    id: "07",
    name: "E-LIBRARY",
    desc: "Advanced library management system with intelligent search and reservation workflows. React frontend, Spring Boot REST API, and MySQL with role-based access.",
    tech: ["React", "Spring Boot", "MySQL", "JavaScript"],
    url: "https://github.com/AmbitiousFlowDev/E-Library",
    category: "WEB APPLICATION",
  },
  {
    id: "08",
    name: "SONA",
    desc: "Minimal Discord bot enhancing server experience with custom automation, commands, and event handling. Built with the Disnake Python framework.",
    tech: ["Python", "Discord", "Disnake", "Bot"],
    url: "https://github.com/AmbitiousFlowDev/Sona",
    category: "BOT / AUTOMATION",
  },
] as const;